### ISSUE TITLE
The Hostile Rifted Enderman may be too Powerful

### ISSUE THREAD

**Issue by CCCClear** [Un-Original1/BeastSlayer#11]
The rifted enderman has high armor in combat, the laser it fires cannot be blocked with a shield, and when attacked, it transmits like a enderman. All these are its powerful performance, which I think makes it unique, and I also like the feeling of fighting against it. 
But it can attack me from dozens of blocks away, and when I'm completely unprepared, especially on a plain with no cover, there's nothing I can do.
I think everything is fine except active attack, maybe you can consider making some changes to that, otherwise I'll have to balance it out by lowering its spawn rate. 
It's just a little suggestion. I really appreciate your work.

**Comment by Un-Original1** [comment]
Yup I realised, worry not, I'll make some changes to balance it.

**Comment by CCCClear** [comment]
The speed with which you respond to player issues is amazing. You are an admirable mod author.
Maybe you can close this issue now.
