### ISSUE TITLE
Ingame Forge Config settings does nothing

### ISSUE THREAD

**Issue by RegensteineR1999** [Un-Original1/BeastSlayer#13]
Hey,
currently I try to implement your mod to my modpack. My friends have made already big progress in gearing up so I decided to editing the default values. 
I pretty enjoy the idea to have a global multiplier and make my friends scream when your ancient beast first appears near their homes :)
So I created a local copy with vanilla Minecraft only with JEI + your mod **(1.9.15 with Forge 14.23.5.2860)**
I always make a fresh instance. So that I can try to reproduce any issue/bugs where no others mod/config could conflict.

**Reproduce:**
Join a world and hit ESC to navigate to Mod Options ->AncientBeast -> config
Now change any value…

Here is my Example:  
I tried to change false to true for Zealot Spawn Everywhere.
I also wanted a health boost for Vessel and set his value to 100.
Now hit done and restart the game.
After booting up again a look in the config confirms that nothing was touched…

**Comment by Un-Original1** [comment]
I have no idea why it doesn't works, for now use ancientbeasts.cfg which should be in the config folder

**Comment by RegensteineR1999** [comment]
Already did that with my editor of choice.
I just wanted to let you know that issue.

**Comment by xJon** [comment]
I can confirm it doesn't work with version `1.9.99999.jar` either, might be best to disable it for now as it's been confusing why the config changes don't work

**Comment by Un-Original1** [comment]
just edit the .cfg directly for now, I still haven't quite figured out why it is so broken.

**Comment by Un-Original1** [comment]
Fixed it with latest alpha release
