### ISSUE TITLE
Copyright infringement notification

### ISSUE THREAD

**Issue by DreadKnight** [Un-Original1/BeastSlayer#15]
I am founder of Ancient Beast. It was just brought to my attention that your project copies my project's name almost fully.
https://AncientBeast.com
https://github.com/FreezingMoon/AncientBeast

You are notified to change your project's name to something non-related that would cause confusion to my game project.
Including over here https://www.curseforge.com/minecraft/mc-mods/ancient-beasts
otherwise the page might be taken down soon and would be sad for you to lose all the progress there, so I'm giving you a fair head start to take action and solve the issue at hand, hopefully as soon as possible and without any incidents.

**Comment by Un-Original1** [comment]
Ok, that is unexpected, however I know a thing or two from how copyright works and I'm pretty sure you can't just take down a project just because of a similar name. Not to mention the difference between both projects one being a minecraft mod and the other being a game, and the fact they don't resemble eachother appart from the name. don't get me wrong, I understand your concern and I'm open to talking about how we can get this sorted out the best way possible.

**Comment by DreadKnight** [comment]
> Ok, that is unexpected, however I know a thing or two from how copyright works and I'm pretty sure you can't just take down a project just because of a similar name. Not to mention the difference between both projects one being a minecraft mod and the other being a game, and the fact they don't resemble eachother appart from the name. don't get me wrong, I understand your concern and I'm open to talking about how we can get this sorted out the best way possible.

It's the same name, just plural form. And they're both related to gaming. I've got numerous emails from concerned people about some other project doing less than this to be honest, using name for company for their steam game. Some other very similar game project, called "Ancient Summoner" did a rebrand on its own in order to not run into any issues later on.
Anyway, you get the idea. It's best for the projects to have very distinctive identity none the less, glad you understand.
I'm hoping to see a proper rename, ideally with research done before in order to avoid stepping on other people's toes.

**Comment by DreadKnight** [comment]
Yeah, unexpected for me as well and I don't want to waste too much time dealing with stuff like this, but as a project founder, I have to wear a lot of hats and do a lot of tasks that aren't too pleasant at times. Anyway, I find the whole situation a bit funny after I've seen your nickname. Got this for you https://www.youtube.com/watch?v=KWo-02Hsab4

**Comment by Un-Original1** [comment]
Ok, I'll settle it this way, I'll contact curseforge to check whether this sort of claim is valid, if it is I'll change the name asap. I get this sort of move might be annoying but I hope you understand that the name also was a part of my mod's identity as well, if I can stay with it I will. If I'm wrong and the claim is valid be sure I'll fix it.

**Comment by DreadKnight** [comment]
> Ok, I'll settle it this way, I'll contact curseforge to check whether this sort of claim is valid, if it is I'll change the name asap. I get this sort of move might be annoying but I hope you understand that the name also was a part of my mod's identity as well, if I can stay with it I will. If I'm wrong and the claim is valid be sure I'll fix it.

You seem to be in some sort of denial stage and it's completely understandable. This is not curseforge's decision. I have copyright on the name for more than two decades now. When you made your mod, you didn't do enough research apparently. Sorry, but you can't keep using the name as it's too similar and in the same field. I suggest you rush finding a new name and do the changes as soon as possible, before I start taking actions. I tried to find the other dude that I got complains about several times before but seems he changed name, instead I found a dlc and an expansion doing the same "Ancient Beasts" crap as well, so I'll be lawyering up next year and take care of all these things if I don't see any results otherwise. Try to see things from my point of view: all these game related thingies keep popping up over night using the same name as my life's work, like there's no such thing as search engines for several decades, diluting branding.
### **You have 90 days to rebrand your project.**

**Comment by DreadKnight** [comment]
I've watched first episode of "Wednesday" show and got some sleep, when I woke up, got this idea inspired by the show:
there's one thing I care more than brand dilution, that is getting marketing. So instead of forcing you to rename, I found a more reasonable and friendly solution where we could come to terms of you using the project name as long as you put a disclaimer in your project descriptions all around saying "This project is not affiliated with [AncientBeast.com](url) 🐺", this means CurseForge project description, README on Github repo, somewhere clearly visible on your Discord and so on; note that the link should be clickable wherever possible, as that's the most important part for me, to get some traffic.

On top of that, since my project is free open source, that means you can implement some of the creatures in your project, provided you credit the Ancient Beast 🐺 project and the artists involved. If that happens, you could even change the wording of the disclaimer to something more friendly: "This project uses creatures from [AncientBeast.com](url) 🐺" and you would have to credit the project and artists involved with making the respective creatures in your credits file and/or page.
This is where you can see an older version of the first set https://ancientbeast.com/documentation/?id=units#creaturegrid

**Comment by Un-Original1** [comment]
I see no need for that, as I already stated, if my project name conflict with yours and curseforge says that your claim is valid I'll change it. I already asked the team in a support ticket how would this proceed and what should I do in this scenario (The reply might be coming in about 2 days), after all we don't want this two projects to be related or confused with, and I think if the claim is valid rebranding will be the healthiest thing to do.

**Comment by Un-Original1** [comment]
Ok, based on curseforge's response I have renamed the mod.
