### ISSUE TITLE
[Suggestion] Ectoplasm ore dictionary support

### ISSUE THREAD

**Issue by xJon** [Un-Original1/BeastSlayer#17]
Fish's Undead Rising is another mod offering new mobs to the game and it also has an Ectoplasm drop (`mod_lavacow:ectoplasm`). The recipes can be manually tweaked but specifically the [LilVessel](https://github.com/Un-Original1/BeastSlayer/blob/master/src/main/java/com/unoriginal/beastslayer/entity/Entities/EntityLilVessel.java#L234) is fussy for which type of Ectoplasm it gets, so full compatibility would be appreciated!

**Comment by xJon** [comment]
I believe just adding ore dictionary support for the [LilVessel](https://github.com/Un-Original1/BeastSlayer/blob/master/src/main/java/com/unoriginal/beastslayer/entity/Entities/EntityLilVessel.java#L234) (and possibly for the recipes) would suffice, then other types of Ectoplasm could be added on the go.

**Comment by Un-Original1** [comment]
Added with latest alpha release. Thanks Jon
