### ISSUE TITLE
Crash on load on Beast Slayer 2.0_test1

### ISSUE THREAD

**Issue by ALJ323** [Un-Original1/BeastSlayer#19]
[crash-2023-06-12_03.56.07-client.txt](https://github.com/Un-Original1/BeastSlayer/files/11719758/crash-2023-06-12_03.56.07-client.txt)
Fresh instance, just the mod by itself, forge 2860.

P.S.
Bring back the Rifted Enderman laser, everyone misses it so much even my grandmother and all the members of her crochet club can testify, its loved, its soulful, and its for the people. Armored Rifted Enderman Laser candidate for 2023, shields need not apply. Nerf him once shame on you, nerf him twice, its a nice change to put the control back in our hands so shame on us for the lack of gratitude. Nerf him thrice and we'll curl up in the corner and weep over our long lost first spring time lover.

**Comment by Un-Original1** [comment]
The issue has been fixed on test1.01, about rifted enderman laser it might be used for another mob as with a teleporting one it was buggy and unfair. Never thought someone liked it that way.
