### ISSUE TITLE
NetherEx Spinout broken ai

### ISSUE THREAD

**Issue by Frosto23** [Un-Original1/BeastSlayer#25]
I don't know if you can fix this on your side but when I have Beast slayer along with NetherEx the Spinout mob ai doesn't work it just stands where it is and never moves or attacks at all.

**Comment by Un-Original1** [comment]
I've been checking netherEx code and I seem to have found the problem (it's rather an unfortunate coincidence), I'll try experimenting with a few things to see if I can fix it without breaking anything.

**Comment by MKxingsheng** [comment]
This problem still exists in beastslayer-2.0.test_1.031. Is there any way to fix it?

**Comment by Un-Original1** [comment]
This issue has been resolved as of latest beta version, I'm closing this issue for now
