### ISSUE TITLE
Mobs not spawning in biomes of plenty biomes?

### ISSUE THREAD

**Issue by IdkWhatNameThingyToPut** [Un-Original1/BeastSlayer#26]
I haven't seen mobs spawning from this mod much and so I used the TellMe mod to dump mob biome spawns and I don't see the mobs listed in any biomes of plenty biomes but I do see them in vanilla biomes. I have seen some of the mobs before and I think this mod is cool af so I thought I would put this here I'm going to assume it doesn't support biomes of plenty biomes? Really hoping you could change that and add support for modded biomes. 

 This is all happened on modded minecraft 1.12.2 btw.

**Comment by Un-Original1** [comment]
I'm aware this has been an issue in the mod for a long time, I would recommend that you use the latest beta version (2.0 test 1.04) where that bug is fixed.

**Comment by IdkWhatNameThingyToPut** [comment]
Ohh ok I think when I installed it on CurseForge it automatically installed a different version just thought I'd mention that to make sure your aware it's doing that

Anyway tyty very much I dumped mob biome spawns with the TellMe mod again and everything looks good, seems to be spawning in biomes of plenty biomes and also stuff from AbyssalCraft, GalaxySpace, MorePlanets, Project Vibrant Journey,  Traverse and maybe even more.

Good job.

**Comment by IdkWhatNameThingyToPut** [comment]
Hi I'm back again I realized after dumping mob biome spawns with the TellMe mod again that it seems like the giant from this mod has only 2 biomes it spawns in which are minecraft:plains and minecraft:mutated_plains

A bunch of the mobs are spawning more with the beta version you told me to download but that giant mob might need more biome spawns and there may be more that also need more biome spawns that I haven't noticed yet so I'm going to put the file with all the spawns I dumped with the TellMe mod so you check for yourself

[biomes-with-mob-spawns_2024-10-31_20.02.47.txt](https://github.com/user-attachments/files/17586789/biomes-with-mob-spawns_2024-10-31_20.02.47.txt)

**Comment by Un-Original1** [comment]
Some mobs are intended to be found only on specific biome types, however I might revisit a few, like giant, and add them more biomes. Sadly it might take a while due to an issue with my old pc.

**Comment by IdkWhatNameThingyToPut** [comment]
> Some mobs are intended to be found only on specific biome types, however I might revisit a few, like giant, and add them more biomes. Sadly it might take a while due to an issue with my old pc.

That's ok I understand if you can't make changes and stuff right now, I do really suggest making the giant spawn in more biomes though please if you ever update the mod that would be amazing.

However for now I have actually got the giant mob spawning in what I think is nearly every biome/modded biomes (I couldn't get the "SANDY" biometype to work with the In Control mod I think not sure why)

If anyone sees this and wants the giant mob to spawn more the solution for now until this mod gets updated is this:

Use the In Control mod and go to the config files then add these:

In potentialspawn.json:
[
{
"dimension": 0,
"biometype": ["WARM", "COLD", "FOREST", "JUNGLE", "BEACH", "SNOWY", "SAVANNA", "SPARSE", "MOUNTAIN", "SWAMP", "CONIFEROUS", "HOT", "SPOOKY", "RARE", "MESA", "DRY", "HILLS", "MUSHROOM", "PLAINS", "DEAD", "LUSH", "WASTELAND", "MAGICAL", "TWILIGHT", "NETHER"],
"mobs": [
{
"mob": "ancientbeasts:giant_zombie",
"weight": 500,
"groupcountmin": 1,
"groupcountmax": 2
}
]
}
]

In spawn.json:

[
{
"mob": "ancientbeasts:giant_zombie",
"onjoin": true,
"mincount": {
"amount": 1
},
"result": "deny"
},
{
"mob": "ancientbeasts:giant_zombie",
"onjoin": true,
"seesky": true,
"result": "deny"
}
]

You can change how much the mobs spawn by adjusting the "weight": 30 to whichever number you want (lower means it might spawn less, higher means it might spawn more) and for reference a zombie's "weight" I think is 95

Also you change the number near "amount" to adjust how many of the giant mobs you would like to spawn.

Also you don't have to worry about them spawning in caves and glitching out or anything because they're a huge mob and stuff because "seesky": true," stops them from spawning in caves.

**Comment by IdkWhatNameThingyToPut** [comment]
Hello just saying I ran into problems with that config setup for the In Control mod on my other comment but after talking to the dev of the In Control mod on this post https://github.com/McJtyMods/InControl/issues/456 it seems to be fixed and done properly now, I've updated my other comment here with the working config setup.

**Comment by Un-Original1** [comment]
I have increased the biome variety of most of the mobs, given that adding Giant to more biomes do no longer fits as a "bug" (and the bop issue has already been fixed) I'm marking this issue as resolved.
