### ISSUE TITLE
Astral Sorcery cannot be creatively flown!

### ISSUE THREAD

**Issue by magmagdigdig** [Un-Original1/BeastSlayer#5]
Creative flight by astral sorcery vicio capes is not possible.

**Comment by magmagdigdig** [comment]
This bug does not occur in 1.0.11

**Comment by Un-Original1** [comment]
I will search in astral sorcery code for a solution, yet due to it being quite a huge mod it might take some time

**Comment by Un-Original1** [comment]
So, I think I found the solution, do vicio capes work just as elytras or do something more? (I don't play with astral sorcery that much so I don't know if it is solved)

**Comment by magmagdigdig** [comment]
create creative world.

use scroll of written expertise (massive knowledge).

use irradiant star (vicio).
press and hold the right mouse button until the star breaks.

enter the command
/astralsorcery exp USERNAME 600000
USERNAME should be your player name.

open astral tome.
open the Perks tab on the right side of the book.

get Spectral wings at the bottom of the perk.
need to get one perk at a time, from root vicio to spectral wings.

Equip Mantle of Stars (Vicio)

Set the game mode to survival.

now ready to fly.

**Comment by Un-Original1** [comment]
Apparently I fixed it, so I will be uploading the jar likely tomorrow cuz it's like 12AM in my country

**Comment by magmagdigdig** [comment]
The problem has been fixed.
Thank you.
