### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by celophys** [Un-Original1/BeastSlayer#7]
Crash with gargoyles mod, with the last version of the mod

![Desktop Screenshot 2021 11 07 - 13 53 04 04](https://user-images.githubusercontent.com/84269120/140645739-d645e0bd-1998-4950-908b-4b4360a6d529.png)
( i use vanllafix mod that indicates the mods that causes the issues )

**Comment by Un-Original1** [comment]
Got the crash log? I can't do much without the crash log.

**Comment by celophys** [comment]
[crash-2021-11-08_09.05.43-client.txt](https://github.com/Un-Original1/AncientBeasts/files/7495236/crash-2021-11-08_09.05.43-client.txt)

here, thanks for the response! (i am not english)

**Comment by celophys** [comment]
this problem arrived in version 1.3 of ancient beasts, before it worked fine

**Comment by Un-Original1** [comment]
Ok, found the problem, essentially gargoyles and my mod used a same entity id which is crashing the game, this will be fixed on the next update.

**Comment by celophys** [comment]
Ok thanks!!

**Comment by Un-Original1** [comment]
Fixed on the new update
